apiVersion: v1
kind: Service
metadata:
  name: nodeport-juan-gomez
  namespace: namespace-juan-gomez
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007