apiVersion: v1
kind: Pod
metadata:
  name: pod-santiago-giraldo
  namespace: namespace-santiago-giraldo
spec:
  containers:
  - name: httpd
    image: 590183924888.dkr.ecr.us-east-1.amazonaws.com/repositorio-santiago-giraldo:latest
    ports:
    - containerPort: 80
