apiVersion: v1
kind: Service
metadata:
  name: servicio-santiago-giraldo
  namespace: namespace-santiago-giraldo
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80